### ISSUE TITLE
binaries for other platforms

### ISSUE THREAD

**Issue by nakshay** [phlummox-dev/redis-static-binaries#3]
By any chance binaries for other major platform can be provided? windows and macos only ?
I am trying to build statically linked binaries for redis-server but facing issues, any guide or link if you can provide to build statically

**Comment by phlummox** [comment]
Unfortunately not - the repository is intended solely for my own use, and I don't use Redis on Windows or MacOS. If the statically linked Redis binaries I've created for Linux turn out to be useful to someone, then that's great, but I don't plan to expand the scope of the repository.

You can see how the build is done just by looking in the [build.yaml file](https://github.com/phlummox-dev/redis-static-binaries/blob/10480a2424669105f95f3c3974f18a05f24c5047/.github/workflows/build.yml#L35) used by GitHub Actions - it really does nothing more than set `CFLAGS` and `LDFLAGS` to `-static` when invoking `make`. Since that worked for me, that's the extent of my knowledge on the subject, I'm afraid.

I wish you the best of luck with your build!
